name: wc_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  test_process: ^2.1.0
